version: '2'
services:
    node-cli:
        image: node:5
        env_file: .env
        entrypoint: bash
        working_dir: /app
        ports:
            - "8082:8082"
        volumes:
            - .:/app
    dev:
        image: node:5
        env_file: .env
        entrypoint: npm run start:dev
        working_dir: /app
        ports:
            - "8082:8082"
        volumes:
            - .:/app
        links:
            - redis
    redis:
        image: redis:3
        ports:
          - "6379:6379"
